title: Site

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea
    buttons: 

  meta_image: 
    label: Meta Image (for social sharing etc)
    type: image